export const Arachnid = {
  name: "Arachnid",
  i: 40,
  min: 4,
  max: 10,
  d: "erlsk",
  m: 0,
  b: [
    "Aaqok'ser", "Aiced", "Aizachis", "Allinqel", "As'taq", "Ashrash", "Caaqtos",
    "Ceek'sax", "Ceezuq", "Cek'sier", "Cen'qi", "Ceqzocer", "Cezeed", "Chachocaq",
    "Charis", "Chashilieth", "Checib", "Chernul", "Chezi", "Chiazu", "Chishros",
    "Chixhi", "Chizhi", "Chollash", "Choq'sha", "Cinchichail", "Collul", "Ecush'taid",
    "Ekiqe", "Eqas", "Er'uria", "Erikas", "Es'tase", "Esrub", "Exha", "Haqsho",
    "Hiavheesh", "Hitha", "Hok'thi", "Hossa", "Iacid", "Iciever", "Illuq", "Isnir",
    "Keezut", "Kheellavas", "Kheizoh", "Khiachod", "Khika", "Khirzur", "Khonrud",
    "Khrakku", "Khraqshis", "Khrethish'ti", "Khriashus", "Khrika", "Khrirni",
    "Klashirel", "Kleil'sha", "Klishuth", "Krarnit", "Kras'tex", "Krotieqas",
    "Lais'tid", "Laizuh", "Lasnoth", "Len'qeer", "Leqanches", "Lezad", "Lhilir",
    "Lhivhath", "Lhok'thu", "Lialliesed", "Liaraq", "Liceva", "Lichorro", "Lilla",
    "Lokieqib", "Nakur", "Neerhaca", "Neet'er", "Neezoh", "Nenchiled", "Nerhalneth",
    "Nir'ih", "Nizus", "Noreeqo", "On'qix", "Qalitho", "Qas'tor", "Qasol", "Qavrud",
    "Qavud", "Qazar", "Qazru", "Qekno", "Qeqravee", "Qes'tor", "Qhaik'sal", "Qhak'sish",
    "Qhazsakais", "Qheliva", "Qhenchaqes", "Qherazal", "Qhon'qos", "Qhosh", "Qish'tur",
    "Qisih", "Qorhoci", "Qranchiq", "Racith", "Rak'zes", "Ranchis", "Rarhie", "Rarzi",
    "Rarzisiaq", "Ras'tih", "Ravosho", "Recad", "Rekid", "Rernee", "Rertachis",
    "Rezhokketh", "Reziel", "Rhacish", "Rhail'shel", "Rhairhizse", "Rhakivex",
    "Rhaqeer", "Rhartix", "Rheciezsei", "Rheevid", "Rhel'shir", "Rhevhie", "Rhiavekot",
    "Rhikkos", "Rhiqese", "Rhiqi", "Rhiqracar", "Rhisned", "Rhousnateb", "Riakeesnex",
    "Rintachal", "Rir'ul", "Rourk'u", "Rouzakri", "Sailiqei", "Sanchiqed", "Saqshu",
    "Sat'ier", "Sazi", "Seiqas", "Shieth'i", "Shiqsheh", "Shizha", "Shrachuvo",
    "Shranqo", "Shravhos", "Shravuth", "Shreerhod", "Shrethuh", "Shriantieth",
    "Shronqash", "Shrovarhir", "Shrozih", "Siacaqoh", "Siezosh", "Siq'sha", "Sirro",
    "Sornosi", "Srachussi", "Szaca", "Szacih", "Szaqova", "Szasu", "Szazhilos",
    "Szeerrud", "Szeezsad", "Szeknur", "Szesir", "Szezhirros", "Szilshith", "Szon'qol",
    "Szornuq", "Xeekke", "Yeek'su", "Yeeq'zox", "Yeqil", "Yeqroq", "Yeveed", "Yevied",
    "Yicaveeh", "Yirresh", "Yisie", "Yithik'thaih", "Yorhaqshes", "Zacheek'sa",
    "Zakkasa", "Zelraq", "Zeqo", "Zharuncho", "Zhath'arhish", "Zhavirrit", "Zhazilraq",
    "Zhazsachiel", "Zhek'tha", "Zhequ", "Zhias'ted", "Zhicat", "Zhicur", "Zhirhacil",
    "Zhizri", "Zhochizses", "Ziarih", "Zirnib"
  ]
};
