export const Draconic = {
  name: "Draconic",
  i: 39,
  min: 6,
  max: 14,
  d: "aliuszrox",
  m: 0,
  b: [
    "Aaronarra", "Adalon", "Adamarondor", "Aeglyl", "Aerosclughpalar", "Aghazstamn", "Aglaraerose",
    "Agoshyrvor", "Alduin", "Alhazmabad", "Altagos", "Ammaratha", "Amrennathed", "Anaglathos",
    "Andrathanach", "Araemra", "Araugauthos", "Arauthator", "Arharzel", "Arngalor", "Arveiaturace",
    "Athauglas", "Augaurath", "Auntyrlothtor", "Azarvilandral", "Azhaq", "Balagos", "Baratathlaer",
    "Bleucorundum", "BrazzPolis", "Canthraxis", "Capnolithyl", "Charvekkanathor", "Chellewis",
    "Chelnadatilar", "Cirrothamalan", "Claugiyliamatar", "Cragnortherma", "Dargentum",
    "Dendeirmerdammarar", "Dheubpurcwenpyl", "Domborcojh", "Draconobalen", "Dragansalor",
    "Dupretiskava", "Durnehviir", "Eacoathildarandus", "Eldrisithain", "Enixtryx", "Eormennoth",
    "Esmerandanna", "Evenaelorathos", "Faenphaele", "Felgolos", "Felrivenser", "Firkraag",
    "Fll'Yissetat", "Furlinastis", "Galadaeros", "Galglentor", "Garnetallisar", "Garthammus",
    "Gaulauntyr", "Ghaulantatra", "Glouroth", "Greshrukk", "Guyanothaz", "Haerinvureem",
    "Haklashara", "Halagaster", "Halaglathgar", "Havarlan", "Heltipyre", "Hethcypressarvil",
    "Hoondarrh", "Icehauptannarthanyx", "Iiurrendeem", "Ileuthra", "Iltharagh", "Ingeloakastimizilian",
    "Irdrithkryn", "Ishenalyr", "Iymrith", "Jaerlethket", "Jalanvaloss", "Jharakkan",
    "Kasidikal", "Kastrandrethilian", "Khavalanoth", "Khuralosothantar", "Kisonraathiisar",
    "Kissethkashaan", "Kistarianth", "Klauth", "Klithalrundrar", "Krashos", "Kreston",
    "Kriionfanthicus", "Krosulhah", "Krustalanos", "Kruziikrel", "Kuldrak", "Lareth",
    "Latovenomer", "Lhammaruntosz", "Llimark", "Ma'fel'no'sei'kedeh'naar", "MaelestorRex",
    "Magarovallanthanz", "Mahatnartorian", "Mahrlee", "Malaeragoth", "Malagarthaul",
    "Malazan", "Maldraedior", "Maldrithor", "MalekSalerno", "Maughrysear", "Mejas",
    "Meliordianix", "Merah", "Mikkaalgensis", "Mirmulnir", "Mistinarperadnacles", "Miteach",
    "Mithbarazak", "Morueme", "Moruharzel", "Naaslaarum", "Nahagliiv", "Nalavarauthatoryl",
    "Naxorlytaalsxar", "Nevalarich", "Nolalothcaragascint", "Nurvureem", "Nymmurh",
    "Odahviing", "Olothontor", "Ormalagos", "Otaaryliakkarnos", "Paarthurnax", "Pelath",
    "Pelendralaar", "Praelorisstan", "Praxasalandos", "Protanther", "Qiminstiir",
    "Quelindritar", "Ralionate", "Rathalylaug", "Rathguul", "Rauglothgor", "Raumorthadar",
    "Relonikiv", "Ringreemeralxoth", "Roraurim", "Rynnarvyx", "Sablaxaahl", "Sahloknir",
    "Sahrotaar", "Samdralyrion", "Saryndalaghlothtor", "Sawaka", "Shalamalauth", "Shammagar",
    "Sharndrel", "Shianax", "Skarlthoon", "Skurge", "Smergadas", "Ssalangan", "Sssurist",
    "Sussethilasis", "Sylvallitham", "Tamarand", "Tantlevgithus", "Tarlacoal", "Tenaarlaktor",
    "Thalagyrt", "Tharas'kalagram", "Thauglorimorgorus", "Thoklastees", "Thyka",
    "Tsenshivah", "Ueurwen", "Uinnessivar", "Urnalithorgathla", "Velcuthimmorhar", "Velora",
    "Vendrathdammarar", "Venomindhar", "Viinturuth", "Voaraghamanthar", "Voslaarum",
    "Vr'tark", "Vrondahorevos", "Vuljotnaak", "Vulthuryol", "Wastirek", "Worlathaugh",
    "Xargithorvar", "Xavarathimius", "Yemere", "Ylithargathril", "Ylveraasahlisar",
    "Za-Jikku", "Zarlandris", "Zellenesterex", "Zilanthar", "Zormapalearath",
    "Zundaerazylym", "Zz'Pzora"
  ]
};