export const Serpents = {
  name: "Serpents",
  i: 41,
  min: 5,
  max: 11,
  d: "slrk",
  m: 0,
  b: [
    "Aj'ha", "Aj'i", "Aj'tiss", "Ajakess", "Aksas", "Aksiss", "Al'en", "An'jeshe",
    "Apjige", "Arkkess", "Athaz", "Atus", "Azras", "Caji", "Cakrasar", "Cal'arrun",
    "Capji", "Cathras", "Cej'han", "Ces", "Cez'jenta", "Cij'te", "Cinash", "Cizran",
    "Coth'jus", "Cothrash", "Culzanek", "Cunaless", "Ej'tesh", "Elzazash", "Ergek",
    "Eshjuk", "Ethris", "Gan'jas", "Gapja", "Gar'thituph", "Gopjeguss", "Gor'thesh",
    "Gragishaph", "Grar'theness", "Grath'ji", "Gressinas", "Grolzesh", "Grorjar",
    "Grozrash", "Guj'ika", "Harji", "Hej'hez", "Herkush", "Horgarrez", "Illuph",
    "Ipjar", "Ithashin", "Kaj'ess", "Kar'kash", "Kepjusha", "Ki'kintus", "Kissere",
    "Koph", "Kopjess", "Kra'kasher", "Krak", "Krapjez", "Krashjuless", "Kraz'ji",
    "Krirrigis", "Krussin", "Ma'lush", "Mage", "Maj'tak", "Mal'a", "Mapja", "Mar'kash",
    "Mar'kis", "Marjin", "Mas", "Mathan", "Men'jas", "Meth'jaresh", "Mij'hegak",
    "Min'jash", "Mith'jas", "Monassu", "Moss", "Naj'hass", "Najugash", "Nak",
    "Napjiph", "Nar'ka", "Nar'thuss", "Narrusha", "Nash", "Nashjekez", "Nataph",
    "Nij'ass", "Nij'tessiph", "Nishjiss", "Norkkuss", "Nus", "Olluruss", "Or'thi",
    "Or'thuss", "Paj'a", "Parkka", "Pas", "Pathujen", "Paz'jaz", "Pepjerras",
    "Pirkkanar", "Pituk", "Porjunek", "Pu'ke", "Ragen", "Ran'jess", "Rargush",
    "Razjuph", "Rilzan", "Riss", "Rithruz", "Rorgiss", "Rossez", "Rraj'asesh",
    "Rraj'tass", "Rrar'kess", "Rrar'thuph", "Rras", "Rrazresh", "Rrej'hish",
    "Rrigelash", "Rris", "Rris", "Rroksurrush", "Rukrussush", "Rurri", "Russa",
    "Ruth'jes", "Sa'kitesh", "Sar'thass", "Sarjas", "Sazjuzush", "Ser'thez", "Sezrass",
    "Shajas", "Shas", "Shashja", "Shass", "Shetesh", "Shijek", "Shun'jaler",
    "Shurjarri", "Skaler", "Skalla", "Skallentas", "Skaph", "Skar'kerriz",
    "Skath'jeruk", "Sker'kalas", "Skor", "Skoz'ji", "Sku'lu", "Skuph", "Skur'thur",
    "Slalli", "Slalt'har", "Slelziress", "Slil'ar", "Sloz'jisa", "Sojesh", "Solle",
    "Sorge", "Sral'e", "Sran'ji", "Srapjess", "Srar'thazur", "Srash", "Srath'jess",
    "Srathrarre", "Srerkkash", "Srus", "Sruss'tugeph", "Sun", "Suss'tir", "Uzrash",
    "Vargush", "Vek", "Vess'tu", "Viph", "Vult'ha", "Vupjer", "Vushjesash", "Xagez",
    "Xassa", "Xulzessu", "Zaj'tiss", "Zan'jer", "Zarriss", "Zassegus", "Zirres",
    "Zsor", "Zurjass"
  ]
};
